### ISSUE TITLE
Taxonomy and Media is not indexed to Triplestore

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/triplestore_indexer#6]
## About
Node has indexing to Triplestore as action. 
Need to create the same actions for taxonomy and media

## How to produce it 
* Run up the isle-lite-dc
* Have some content created or ingested, also have content reference to taxonomy term(s)
* Go to `/admin/content`, and select node(s), and the select an action "Index node to Triplestore (Via Advanced Queue)"
* Go to Configuration > Queue > Triplestore queue, to see if the job is executed successfully. 
* Go to blazegraph endpoint https://islandora.traefik.me:8082/bigdata run a basic [SPARQL](https://codyburleson.com/blog/sparql-examples-select)  query to see if the content is index to blazegraph  
* From the result, the node should be index, however the taxonomy is not being indexed. 

## TODO
* In islandora (https://sandbox.islandora.ca/admin/config/system/actions), they have actions `Index Taxonomy Term in the Triplestore` and `Delete Taxonomy Term in Triplestore`. 
* Create actions: 
   * Index Taxonomy Term in the Triplestore
   * Delete Taxonomy Term in Triplestore
   * Index Media in the Triplestore
   * Delete Media in Triplestore
* These action will be similar to the ones for nodes (https://github.com/digitalutsc/triplestore_indexer/tree/8.x-1.x/src/Plugin/Action), will do: 
  * Queue a job to Advanced Queue, 
  * Each job will serialize the Taxonomy Term via JsonLD module, and send a REST request to Blazegraph

**Comment by amym-li** [comment]
Some of the taxonomy terms in Islandora Lite have an `owl:sameAs` property which causes an error when indexing if the owl namespace is not configured.

To configure it:
- Go to `/admin/config/search/jsonld`
- Under Additional RDF Namespaces, add the line: 
`owl|http://www.w3.org/2002/07/owl#`
