### ISSUE TITLE
Unable to delete a node which has access control with Group

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/triplestore_indexer#9]
The module: https://www.drupal.org/project/triplestore_indexer

# How to reproduce? 

* Have the isle-dc up running 
* Create a node with a media 
* Create a group 
* Assign the newly created node to that newly created group
* Delete the node, the white screen will appear 

# Diagnosis 

* Workflow to delete a node: (code is here https://github.com/digitalutsc/triplestore_indexer/blob/8.x-1.x/src/Plugin/AdvancedQueue/JobType/TriplestoreIndexJob.php#L49-L62)
    *  Make the rest request to `/node/...?_format=jsonld` 
    * Get the serialization and then send it to the Blazegraph to delete the record there
    * When that's done, the delete node in Drupal action is started. 
* Because the node is in private mode the rest endpoint of `node/...?format=jsonld` has 401 error. That cause the white screen

# Goal 
* Find and handle where is the crash error 
* Resolve the issue by finding a way to handle the 401 error of the rest endpoint `node/...?format=jsonld` if the node is in access control.  ==> maybe use JWT token to get authenticated to the jsonld endpoint. (ie. https://github.com/digitalutsc/islandora_mirador/blob/drupal_mirador/islandora_mirador.module#L34)

**Comment by HyphenHook** [comment]
# Encountered
Error: Call to a member function getGroupType() on null in Drupal\search_api\Plugin\views\filter\SearchApiLanguage->query() (line 33 of /var/www/drupal/web/modules/contrib/search_api/src/Plugin/views/filter/SearchApiLanguage.php).
On deleting group indexed item. 

Edit: This was an error encountered due to a module I installed and nothing to do with search_api

**Comment by HyphenHook** [comment]
# Workaround
In ```Configuration > System > Triplestore Indexer``` there is an option to enable ```Basic Authentication``` under ```Drupal Authentication```. It requires an administrator account to allow for endpoint access thus avoiding the 401 error.  
Will look into incorporating JWT tokens instead of Basic Auth for security.
